# update default cursor color
cursor #ffffff

# custom url styling
url_color #0087bd
url_style curly
open_url_modifiers kitty_mod

# custom keybinding for fullscreen
map f11 toggle_fullscreen

# setting background color
background #202020

window_padding_width 10.0
