# update default cursor color
font_family Source Code Pro
cursor #ffffff

# custom url styling
url_color #0087bd
url_style curly
open_url_modifiers kitty_mod

# custom keybinding for fullscreen
map f11 toggle_fullscreen

# setting background color
background #545454

window_padding_width 10.0
