set -g mouse on
set -g status-style "bg=#263231"
set -g status-left-length 50
set -g status-left '#S  |  git: #(git -C "#{pane_current_path}" branch --show-current 2>/dev/null)  '
set -g status-right '#{?client_prefix,#[bold]PREFIX#[default],}'
set -g pane-border-style "fg=#263231"
set -g pane-active-border-style "fg=#263238"

# Split panes with | and -
bind | split-window -h
bind - split-window -v

# New window with n
bind n new-window

# Reload config with prefix + r
bind r source-file ~/.tmux.conf

# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'ChanderG/tmux-notify'

# Initialize TPM (keep this at the bottom of the file)
run '~/.tmux/plugins/tpm/tpm'
