#!/bin/sh

# Check if the dotfiles are cloned and if not clone them
if [ -d ~/.dotfiles/ ]; then
    echo "[dotfiles] ~/.dotfiles directory already exists!"
else
    git clone https://github.com/AndrewRPorter/dotfiles.git ~/.dotfiles
fi

# Install Oh My Zsh
echo "[dotfiles] Installing oh my zsh"
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    /bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
else
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

echo "[dotfiles] Setting up ZSH auto-suggestions"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions