#!/bin/bash

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # note we pipe "yes n" into this apt install to preserve
    # the z login file. Otherwise, this install will overwrite it
    yes n | sudo sudo apt-get --assume-yes install zsh
fi

# Set ZSH as default shell
sudo chsh -s /bin/zsh $(whoami)

# Install Oh My Zsh
echo "[dotfiles] Installing oh my zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo "[dotfiles] Setting up ZSH auto-suggestions"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# Create symlink of all dotfiles to home directory
cwd=$(pwd)
ln -sf $cwd/.zshrc ~/.zshrc
