#!/bin/bash

# attempt to install ZSH shell
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get update
    # note we pipe "yes n" into this apt install to preserve
    # the z login file. Otherwise, this install will overwrite it
    echo "[dotfiles] installing ZSH"
    yes n | sudo apt -y install zsh

    echo "[dotfiles] installing VIM"
    sudo apt -y install vim

    # setup rbenv and ruby-build for codespaces
    echo "[dotfiles] installing rbenv and configure ruby-build"
    sudo apt -y install rbenv
    git clone https://github.com/rbenv/ruby-build.git "$(rbenv root)"/plugins/ruby-build 
fi

# set ZSH as default shell
if [[ "$SHELL" != "/bin/zsh"* ]]; then
    sudo chsh -s /bin/zsh $(whoami)
fi

# install oh my zsh
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
    echo "[dotfiles] Installing oh my zsh"
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# install oh my zsh plugins
if [[ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-autosuggestions" ]]; then
    echo "[dotfiles] Setting up ZSH auto-suggestions"
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

# create symlink of all dotfiles to home directory
cwd=$(pwd)
ln -sf $cwd/.zshrc ~/.zshrc
